/*
 * Copyright 2011-2013 Ayla Networks, Inc.  All rights reserved.
 *
 * Use of the accompanying software is permitted only in accordance
 * with and subject to the terms of the Software License Agreement
 * with Ayla Networks, Inc., a copy of which can be obtained from
 * Ayla Networks, Inc.
 */
	/*
	 * These name/pairs must not change after the first release for
	 * upward compatibility with older configurations or customer code.
	 */
	/* 0 is absolutely reserved as an error return, do not use otherwise */
	CONF_TOKEN(0x01, enable)
	CONF_TOKEN(0x02, ready)
	CONF_TOKEN(0x03, sys)
	CONF_TOKEN(0x04, wifi)
	CONF_TOKEN(0x05, server)
	CONF_TOKEN(0x06, client)
	CONF_TOKEN(0x07, ssl)
	CONF_TOKEN(0x08, status)
	CONF_TOKEN(0x09, start)
	CONF_TOKEN(0x0a, complete)
	CONF_TOKEN(0x0b, ip)
	CONF_TOKEN(0x0c, n)		/* indicates an index follows */
	CONF_TOKEN(0x0d, time)
	CONF_TOKEN(0x0e, power)
	CONF_TOKEN(0x0f, user)
	CONF_TOKEN(0x10, version)
	CONF_TOKEN(0x11, file)
	CONF_TOKEN(0x12, name)
	CONF_TOKEN(0x13, type)
	CONF_TOKEN(0x14, model)
	CONF_TOKEN(0x15, serial)
	CONF_TOKEN(0x16, mfg_serial)
	CONF_TOKEN(0x17, hostname)
	CONF_TOKEN(0x18, timezone)
	CONF_TOKEN(0x19, timezone_valid)
	CONF_TOKEN(0x1a, mfg_mode)
	CONF_TOKEN(0x1b, dev_id)
	CONF_TOKEN(0x1c, setup_mode)
	CONF_TOKEN(0x1d, mfg_model)
	CONF_TOKEN(0x1e, sim)
	CONF_TOKEN(0x1f, reset)
	CONF_TOKEN(0x20, region)
	CONF_TOKEN(0x21, acc)
	CONF_TOKEN(0x22, char)
	/* reserved gap */
	CONF_TOKEN(0x25, profile)
	CONF_TOKEN(0x26, ssid)
	CONF_TOKEN(0x27, security)
	CONF_TOKEN(0x28, none)
	CONF_TOKEN(0x29, WEP)
	CONF_TOKEN(0x2a, WPA)
	CONF_TOKEN(0x2b, WPA2_Personal)
	CONF_TOKEN(0x2c, key)
	CONF_TOKEN(0x2d, pri)
	CONF_TOKEN(0x2e, scan)
	CONF_TOKEN(0x2f, time_limit)
	CONF_TOKEN(0x30, save_on_ap_connect)
	CONF_TOKEN(0x31, save_on_server_connect)
	CONF_TOKEN(0x32, max_perf)
	CONF_TOKEN(0x33, en_bind)
	CONF_TOKEN(0x34, ap_mode)
	CONF_TOKEN(0x35, rssi)
	CONF_TOKEN(0x36, bssid)
	CONF_TOKEN(0x37, bars)
	CONF_TOKEN(0x38, poll_interval)
	CONF_TOKEN(0x39, addr)
	CONF_TOKEN(0x3a, mac_addr)
	CONF_TOKEN(0x3b, ant)
	CONF_TOKEN(0x3c, test)
	/* reserved gap */
	CONF_TOKEN(0x43, connected)
	CONF_TOKEN(0x44, cert)
	CONF_TOKEN(0x45, private_key)
	CONF_TOKEN(0x46, ca)
	CONF_TOKEN(0x47, gif)
	CONF_TOKEN(0x48, oem)
	CONF_TOKEN(0x49, log)
	CONF_TOKEN(0x4a, mod)
	CONF_TOKEN(0x4b, mask)
	CONF_TOKEN(0x4c, chan)
	CONF_TOKEN(0x4d, error)
	CONF_TOKEN(0x4e, link)
	CONF_TOKEN(0x4f, reg)
	CONF_TOKEN(0x50, default)
	CONF_TOKEN(0x51, min)
	CONF_TOKEN(0x52, standby)
	CONF_TOKEN(0x53, mode)
	CONF_TOKEN(0x54, dhcp)
	CONF_TOKEN(0x55, gw)
	CONF_TOKEN(0x56, snapshot)
	CONF_TOKEN(0x57, hist)
	CONF_TOKEN(0x58, source)
	CONF_TOKEN(0x59, WPS)
	CONF_TOKEN(0x5a, listen)
	CONF_TOKEN(0x5b, interval)
	CONF_TOKEN(0x5c, auto)
	CONF_TOKEN(0x5d, current)
	CONF_TOKEN(0x5e, awake_time)
	CONF_TOKEN(0x5f, standby_powered)
	CONF_TOKEN(0x60, unconf_powered)
	CONF_TOKEN(0x61, metric)
	CONF_TOKEN(0x62, http)
	CONF_TOKEN(0x63, tcp)
	CONF_TOKEN(0x64, count)
	CONF_TOKEN(0x65, locale)
	CONF_TOKEN(0x66, lan)
	CONF_TOKEN(0x67, setup_ios_app)
	CONF_TOKEN(0x68, notify)
	CONF_TOKEN(0x69, gpio)
	CONF_TOKEN(0x6a, intr)
	CONF_TOKEN(0x6b, data)
	CONF_TOKEN(0x6c, clock)
	CONF_TOKEN(0x6d, mfi)
	CONF_TOKEN(0x6e, hidden)
	/* reserved gap */
	CONF_TOKEN(0x70, value)
	CONF_TOKEN(0x71, prop)
	CONF_TOKEN(0x72, port)
	CONF_TOKEN(0x73, sched)
	CONF_TOKEN(0x74, dst_active)
	CONF_TOKEN(0x75, dst_change)
	CONF_TOKEN(0x76, dst_valid)
	CONF_TOKEN(0x77, dns)
	CONF_TOKEN(0x78, hw)
	CONF_TOKEN(0x79, rtc_src)
	CONF_TOKEN(0x7a, host)
	CONF_TOKEN(0x7b, uart)
	CONF_TOKEN(0x7c, spi)
	CONF_TOKEN(0x7d, speed)
	CONF_TOKEN(0x7e, eth)
	CONF_TOKEN(0x7f, id)	/* Using for homekit identify */
	/* NB: tokens 0x80 and above require code enhancements */
