#
# Copyright 2017 Ayla Networks, Inc.  All rights reserved.
#

NAME = libada
AYLA_SRC = ..

SOURCES := \
	ada_conf.c \
	ada_err.c \
	client.c \
	client_auth.c \
	client_conf.c \
	client_ota.c \
	client_prop.c \
	conf_json.c \
	lan.c \
	log_page.c \
	notify.c \
	prop_mgr.c \
	prop_page.c \
	oem.c \
	sched.c \
	schedeval.c \
	server_req.c \
	sprop.c	\
	server_mem.c	\
	sys_conf.c \
	al/ameba/ada_lock.c \
	al/ameba/ameba_conf.c	\
	al/ameba/ameba_log.c	\
	al/ameba/client_task.c \
	al/ameba/conf_table.c \
	al/ameba/http_client.c \
	al/ameba/notify_task.c \
	al/ameba/server.c \
	al/ameba/stubs.c \
	al/ameba/sched_conf.c \
	certs/ca_certs_der.c \
	text/custom.css.c \
	text/regtoken.html.c \
	$(NULL)

#	dnss.c \
#	dnss_util.c \

include $(AYLA_SRC)/make/common_defs.mk
include $(AYLA_SRC)/make/common_cc.mk
