#
# Copyright 2017 Ayla Networks, Inc.  All rights reserved.
#

NAME = libnet
AYLA_SRC = ..

SOURCES := \
	ameba/ssl.c \
	ameba/net_realtek.c \
	ameba/net_mbuf.c \
	$(NULL)

include $(AYLA_SRC)/make/common_defs.mk
include $(AYLA_SRC)/make/common_cc.mk
